//
//  BoxArtIndex.swift
//  EmulateurGBA
//
//  The bundled game-identification index behind library box art
//  (BoxArtIndex.json, generated by Tools/build_boxart_index.py from the
//  libretro no-intro DATs). Maps a ROM to its exact thumbnail filename stem
//  on thumbnails.libretro.com three ways, strongest first:
//
//    1. CRC32 of the file  — exact, any language, any filename.
//    2. Header serial      — GBA/NDS only; survives renaming AND trimming.
//    3. Fuzzy title match  — the stems keep No-Intro's native regional
//       titles ("Pokemon - Version Emeraude (France)"), so native-named
//       files match natively. No translation step.
//
//  Loaded lazily off-main on first use (~1 MB JSON); resident afterwards.
//

import Foundation

struct BoxArtCandidate: Equatable {
    /// Thumbnail filename stem (No-Intro name, libretro substitution applied).
    let stem: String
    /// Which tier produced it — becomes the analytics `method` param.
    let method: String
}

final class BoxArtIndex {
    static let shared = BoxArtIndex()

    private struct SystemTable: Decodable {
        let names: [String]
        let crc: [String: Int]
        let serial: [String: Int]
    }
    private struct IndexFile: Decodable {
        let systems: [String: SystemTable]
    }

    private let loadQueue = DispatchQueue(label: "boxart.index.load")
    private var tables: [String: SystemTable]?

    /// Minimum Dice score for a fuzzy match. Below this, showing the save
    /// screenshot beats showing a wrong cover. Always paired with the
    /// token-coverage floor: bigram overlap alone lets a franchise word
    /// carry a ROM hack over the line ("Pokemon Radical Red" scores 0.61
    /// against "Pokemon - Edicion Rubi" on shared bigrams).
    static let fuzzyThreshold = 0.55

    /// A fuzzy match must also contain at least this fraction of the
    /// query's WORDS. Kills franchise-prefix false positives (Radical Red's
    /// "radical"/"red" appear in no real stem -> 1/3, rejected) while
    /// keeping legit shorthand ("Zelda Minish Cap" -> 3/3 in the Zelda
    /// stem). A hack named after its base game still matches the base
    /// cover — the filename says that's what it is.
    static let tokenCoverageFloor = 2.0 / 3.0

    /// False when the bundled JSON is missing or undecodable. Callers must
    /// not record a definitive "no match" in that state — an empty index
    /// would otherwise stamp every game "none" permanently.
    var isLoaded: Bool {
        _ = table(for: .gba)   // force the lazy load
        return !(tables?.isEmpty ?? true)
    }

    // MARK: - Lookups (callable from any queue; loading is serialized)

    func exactName(crc32: UInt32, system: ROMSystemType) -> String? {
        let key = String(format: "%08X", crc32)
        guard let table = table(for: system), let idx = table.crc[key] else { return nil }
        return table.names[idx]
    }

    func serialName(_ serial: String, system: ROMSystemType) -> String? {
        // Serials only identify GBA/NDS carts (GB/GBC headers have no
        // unique code; the DATs carry a handful of stray entries there).
        guard system == .gba || system == .nds, serial.count >= 3,
              let table = table(for: system), let idx = table.serial[serial]
        else { return nil }
        return table.names[idx]
    }

    /// Best fuzzy candidates for a user-chosen name (filename stem or in-app
    /// rename), strongest first. Empty when nothing clears BOTH bars (Dice
    /// on bigrams + token coverage) for at least one query.
    func fuzzyCandidates(for queries: [String], system: ROMSystemType, limit: Int) -> [String] {
        guard let table = table(for: system) else { return [] }
        let prepared = queries.map { (raw: $0, normalized: Self.normalized($0)) }
            .filter { $0.normalized.count >= 4 }
            .map { (bigrams: Self.bigrams($0.normalized), raw: $0.raw) }
            .filter { !$0.bigrams.isEmpty }
        guard !prepared.isEmpty else { return [] }

        var scored: [(score: Double, regionRank: Int, stem: String)] = []
        for stem in table.names {
            let stripped = Self.strippingParentheticals(stem)
            let candidate = Self.bigrams(Self.normalized(stripped))
            guard !candidate.isEmpty else { continue }
            var best = 0.0
            for query in prepared {
                let score = Self.dice(query.bigrams, candidate)
                guard score >= Self.fuzzyThreshold, score > best,
                      Self.tokenCoverage(query: query.raw, candidate: stripped)
                          >= Self.tokenCoverageFloor else { continue }
                best = score
            }
            if best >= Self.fuzzyThreshold {
                scored.append((best, Self.regionRank(of: stem), stem))
            }
        }
        return scored
            .sorted {
                if $0.score != $1.score { return $0.score > $1.score }
                if $0.regionRank != $1.regionRank { return $0.regionRank < $1.regionRank }
                return $0.stem < $1.stem
            }
            .prefix(limit)
            .map(\.stem)
    }

    // MARK: - Loading

    private func table(for system: ROMSystemType) -> SystemTable? {
        loadQueue.sync {
            if tables == nil {
                guard let url = Bundle.main.url(forResource: "BoxArtIndex", withExtension: "json"),
                      let data = try? Data(contentsOf: url),
                      let decoded = try? JSONDecoder().decode(IndexFile.self, from: data)
                else {
                    tables = [:]
                    return
                }
                tables = decoded.systems
            }
        }
        return tables?[system.rawValue]
    }

    // MARK: - Fuzzy matching (pure helpers, unit-tested)

    /// Lowercased, diacritics folded, punctuation collapsed away — so
    /// "Pokémon Émeraude" and "Pokemon - Version Emeraude" compare cleanly.
    static func normalized(_ raw: String) -> String {
        let folded = raw.folding(options: [.diacriticInsensitive, .caseInsensitive],
                                 locale: Locale(identifier: "en_US_POSIX"))
        let scalars = folded.unicodeScalars.map { scalar -> Character in
            CharacterSet.alphanumerics.contains(scalar) ? Character(scalar) : " "
        }
        return String(scalars).split(separator: " ").joined(separator: " ")
    }

    /// Region/language/revision tags dilute similarity scores; strip every
    /// parenthetical group before scoring a candidate stem.
    static func strippingParentheticals(_ name: String) -> String {
        name.replacingOccurrences(of: "\\s*\\([^)]*\\)", with: "",
                                  options: .regularExpression)
            .trimmingCharacters(in: .whitespaces)
    }

    /// Character-bigram multiset (spaces dropped: separator noise like
    /// "Pokemon-Version" must not shift the score).
    static func bigrams(_ normalized: String) -> [String: Int] {
        let chars = Array(normalized.replacingOccurrences(of: " ", with: ""))
        guard chars.count >= 2 else { return [:] }
        var counts: [String: Int] = [:]
        for i in 0..<(chars.count - 1) {
            counts[String(chars[i...i+1]), default: 0] += 1
        }
        return counts
    }

    /// Fraction of the query's words that literally appear in the candidate
    /// (both normalized; the candidate's spaces are dropped so "cap" is
    /// found inside "minishcap").
    static func tokenCoverage(query: String, candidate: String) -> Double {
        let tokens = normalized(query).split(separator: " ")
        guard !tokens.isEmpty else { return 0 }
        let haystack = normalized(candidate).replacingOccurrences(of: " ", with: "")
        let covered = tokens.filter { haystack.contains($0) }.count
        return Double(covered) / Double(tokens.count)
    }

    /// Sørensen-Dice coefficient over bigram multisets: 1.0 = identical.
    static func dice(_ a: [String: Int], _ b: [String: Int]) -> Double {
        guard !a.isEmpty, !b.isEmpty else { return 0 }
        var overlap = 0
        for (gram, countA) in a {
            if let countB = b[gram] { overlap += min(countA, countB) }
        }
        let total = a.values.reduce(0, +) + b.values.reduce(0, +)
        return Double(2 * overlap) / Double(total)
    }

    /// Floor for accepting an identity that comes from INSIDE a modified
    /// file. A ROM hack keeps the base game's header (serial + internal
    /// title), so without a byte-exact CRC match the filename is the only
    /// signal that knows the hack's real identity: a serial match is
    /// accepted only when the filename plausibly names the same game.
    /// 0.5: trimmed "Pokemon Diamond.nds" (~0.75 vs its stem) passes,
    /// "Pokemon Radical Red" (0.44 vs FireRed) is vetoed.
    static let filenameConsistencyFloor = 0.5

    /// True when a user-chosen name (filename or in-app rename) plausibly
    /// names the same game as a thumbnail stem.
    static func filenameIsConsistent(_ title: String, withStem stem: String) -> Bool {
        dice(bigrams(normalized(title)),
             bigrams(normalized(strippingParentheticals(stem)))) >= filenameConsistencyFloor
    }

    /// Tie-break for fuzzy matches that normalize identically across regions
    /// ("Mario Kart DS (USA)" vs "(Europe)" vs "(Japan)"): prefer the release
    /// of the user's own region, then Europe (our market), World, USA.
    static func regionRank(of stem: String, locale: Locale = .current) -> Int {
        let localeRegions: [String: String] = [
            "FR": "France", "DE": "Germany", "IT": "Italy", "ES": "Spain",
            "NL": "Netherlands", "SE": "Sweden", "PT": "Portugal",
            "JP": "Japan", "KR": "Korea", "US": "USA",
        ]
        if let code = locale.region?.identifier,
           let region = localeRegions[code],
           stem.contains("(\(region))") { return 0 }
        if stem.contains("(Europe") || stem.contains(", Europe") { return 1 }
        if stem.contains("(World)") { return 2 }
        if stem.contains("(USA") { return 3 }
        return 4
    }
}
